import "tachyons";
import "#/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { wrapper } from "#/redux/store";
import { Provider } from "react-redux";
import { Layout } from "#/components";

export default function App({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;

  return (
    <Provider store={store}>
      <Head>
        <link rel="preconnect" href="https://robohash.org" />
        <link rel="preconnect" href="https://jsonplaceholder.typicode.com" />
        <link rel="icon" href="/icons/favicon.ico" />
        <link rel="apple-touch-icon" href="/icons/192.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Robofriends</title>
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </Provider>
  );
}
